### ISSUE TITLE
LRM generate mesh but with weird box frame?

### ISSUE THREAD

**Issue by MrForExample** [zjp-shadow/CharacterGen#12]
From:
```python
    def get_geometry(self, scene_code: torch.Tensor) -> Mesh:
        tr.start("Surface extraction")
        mesh: Mesh = self.renderer.isosurface(scene_code)
        tr.end("Surface extraction")
        return mesh
        
    mesh = self.get_geometry(scene_code)
    os.makedirs("./output_raw_mesh", exist_ok=True)
    trimesh.Trimesh(
          vertices=mesh.v_pos.detach().cpu().numpy(),
          faces=mesh.t_pos_idx.detach().cpu().numpy(),
     ).export("./output_raw_mesh/mesh.glb")
```

![Screenshot 2024-07-08 224036](https://github.com/zjp-shadow/CharacterGen/assets/62230687/757f5800-f533-491f-9d9b-a7788675422f)

[output_raw_mesh.zip](https://github.com/user-attachments/files/16138091/output_raw_mesh.zip)

Seems something is wrong with DMTet, Any idea?

**Comment by zjp-shadow** [comment]
Could you show the results in webui ?

**Comment by MrForExample** [comment]
Never mind, it's because my background of the input image to LRM I used has different background color than black
