### ISSUE TITLE
The demo results seemly have some artifacts

### ISSUE THREAD

**Issue by lingtengqiu** [zjp-shadow/CharacterGen#13]
Thanks for your great job.

I saw your demo results that illustrate some artifacts like broken holes?
![image](https://github.com/zjp-shadow/CharacterGen/assets/37240099/e8143046-010c-41e3-8679-dad98118bf38)

Are results right?

Or
Can you give me some suggestions to solve this problem?

**Comment by zjp-shadow** [comment]
This is caused by the laplacian smooth, you can set the iteration to 0. I think this is caused by the vertex which are not merged. I will correct this mistask in the future.

**Comment by lingtengqiu** [comment]
Thanks :)
