### ISSUE TITLE
Pose Guider doesn't work

### ISSUE THREAD

**Issue by Royalvice** [zjp-shadow/CharacterGen#14]
The 'PoseGuider' will never be activated in the code no matter what, because it is forcibly set to None during the pipeline inference, and even if it is passed, using different poses cannot control the multiview results. This method of directly inputting on the latent noise has been proven to be poor in controlling the pose in OpenAnimate (https://github.com/guoqincode/Open-AnimateAnyone/tree/main), and it is necessary to increase the output channels and add them after conv_in.

**Comment by zjp-shadow** [comment]
Thank you for your reminder. Indeed, we have found that the PoseGuider primarily serves as a layout control in our task. Therefore, we have fixed the character's pose to A-pose to facilitate 3D reconstruction.

**Comment by Royalvice** [comment]
Thank you for your reply. Will an effective PoseGuider be trained later?
