### ISSUE TITLE
Please reconsider AGPL - weights are Apache 2.0 but code is AGPL? 

### ISSUE THREAD

**Issue by gfxenjoyer** [zjp-shadow/CharacterGen#27]
You have an incredible project; however, the licensing needs clarification. The [weights on HuggingFace](https://huggingface.co/zjpshadow/CharacterGen/blob/main/README.md) are under Apache 2.0, but you marked the code for CharacterGen as AGPL? Is this your intention?

This makes using the code for CharacterGen legally tricky for developers that want to use your weights.

CharacterGen seems most useful as a library in other larger 3D projects. [ComfyUI-3D-Pack includes it.](https://github.com/MrForExample/ComfyUI-3D-Pack/tree/main/Gen_3D_Modules/CharacterGen) However, technically this is a violation of the AGPL as ComfyUI-3D-Pack is MIT, which is incompatible. AGPL is a viral license so CharacterGen would force ComfyUI-3D-Pack to be AGPL. Since the author of ComfyUI-3D-Pack licensed his project as MIT and has incorporated your code, he has technically violated your license.

It would be better for the ecosystem as a whole for you to license CharacterGen under MIT or Apache 2.0; however, if you do decide to keep the code under AGPL, please clarify the license of the weights.

**Comment by zjp-shadow** [comment]
Thanks for your advice. We want this project can be used in more projects. So we change the license in commit 02453103ecee16a8fd367c193e23bec1c163dfc7. :)
