### ISSUE TITLE
Any info on code release?

### ISSUE THREAD

**Issue by April93** [zjp-shadow/CharacterGen#4]
Repo says "will be available soon" but it's been three months...

**Comment by zjp-shadow** [comment]
Sorry... We will release the inference code in this week...

**Comment by Zhangpei226** [comment]
"I'm really looking forward to the code release. I wanted to ask if the 24GB 4090 can run it?"

**Comment by zjp-shadow** [comment]
> "I'm really looking forward to the code release. I wanted to ask if the 24GB 4090 can run it?"

24GB is enough for inference

**Comment by sora158** [comment]
looking forward to inference stage code release!

**Comment by zjp-shadow** [comment]
we release the inference code now, sorry for delay the date QAQ
