### ISSUE TITLE
Requirements not complete

### ISSUE THREAD

**Issue by moon47usaco** [zjp-shadow/CharacterGen#9]
I tried setting up inside a venv.

I had to install gradio, omegaconf and torch so far...

I stopped at diffusers.

```
(venv) S:\Ai\Repos\CharacterGen>python webui.py
Traceback (most recent call last):
  File "S:\Ai\Repos\CharacterGen\webui.py", line 18, in <module>
    from diffusers import AutoencoderKL, DDIMScheduler
ModuleNotFoundError: No module named 'diffusers'
```

**Comment by zjp-shadow** [comment]
Follow the README. Use `pip install -r requirements.txt`

**Comment by moon47usaco** [comment]
I did that is the point. Several times just to be sure.

**Comment by alexandre-ruffer** [comment]
> I tried setting up inside a venv.
> 
> I had to install gradio, omegaconf and torch so far...
> 
> I stopped at diffusers.
> 
> ```
> (venv) S:\Ai\Repos\CharacterGen>python webui.py
> Traceback (most recent call last):
>   File "S:\Ai\Repos\CharacterGen\webui.py", line 18, in <module>
>     from diffusers import AutoencoderKL, DDIMScheduler
> ModuleNotFoundError: No module named 'diffusers'
> ```

Same thing happening to me

**Comment by zjp-shadow** [comment]
> > I tried setting up inside a venv.
> > I had to install gradio, omegaconf and torch so far...
> > I stopped at diffusers.
> > ```
> > (venv) S:\Ai\Repos\CharacterGen>python webui.py
> > Traceback (most recent call last):
> >   File "S:\Ai\Repos\CharacterGen\webui.py", line 18, in <module>
> >     from diffusers import AutoencoderKL, DDIMScheduler
> > ModuleNotFoundError: No module named 'diffusers'
> > ```
> 
> Same thing happening to me

`diffusers==0.24.0` is shown in [`requirements.txt`](https://github.com/zjp-shadow/CharacterGen/blob/main/requirements.txt), just use pip to install the requirements.
Notice all requirements should be installed successfully.
